# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookkeeper', '0002_auto_20160330_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('material_account', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff1', to='bookkeeper.Account')),
                ('monetary_account', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff2', to='bookkeeper.Account')),
            ],
        ),
    ]
