# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstuff',
            name='material_account',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to='bookkeeper.Account'),
        ),
        migrations.AlterField(
            model_name='foodstuff',
            name='monetary_account',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='bookkeeper.Account'),
        ),
    ]
