# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_auto_20160929_0653'),
        ('bar', '0002_auto_20160330_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_count', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monetary_count', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeper.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rounding', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('markup', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.CashBox')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_actual', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('when', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Product')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.SaleOffer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transactions',
            field=models.ManyToManyField(to='bookkeeper.Transaction'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bar.Recipe'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.RecipeIngredient'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sale_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.SaleOffer'),
        ),
    ]
