# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_foodprovider_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='bookkeeper.Transaction'),
        ),
    ]
