# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_auto_20160330_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='code_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
