# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_auto_20160330_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transactions',
            field=models.ManyToManyField(blank=True, editable=False, to='bookkeeper.Transaction'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transactions',
            field=models.ManyToManyField(blank=True, editable=False, to='bookkeeper.Transaction'),
        ),
    ]
