# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_auto_20160330_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='feasible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='stuff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bar.FoodStuff'),
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='feasible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='bar.Recipe'),
        ),
    ]
