# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_auto_20160401_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.FoodStuff'),
        ),
    ]
