# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_auto_20160401_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
