# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_auto_20160401_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='inventory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
